Varios_Datos = [
    ('Letha Bolt', 'AbrahamAcevedo@gmail.com', '2638 Riverview Pkwy', 'Wabash', '(564) 517-5025', 'M', 'Divorced'),
    ('Vanita Kelleher', 'Jude_High169@gmail.com', 'NULL', 'Concord', '(684) 186-0087', 'F', 'Married'),
    ('Marcos Abraham', 'Bauer@gmail.com', '80 White Woodfort Ln', 'Clayton', '(260) 313-6443', 'M', 'Single'),
    ('Miyoko Mckinney', 'Alarcon@gmail.com', '925 Hope St', 'Scottdale', '(868) 864-8718', 'M', 'Married'),
    ('Adolph Francisco', 'gndd9978@gmail.com', '3755 Red Burwood Way', 'Mount Horeb', '(451) 929-8321', 'M', 'Single'),
    ('Oma Lawler', 'NULL', 'NULL', 'Kings Point', '(133) 683-0582', 'F', 'Single'),
    ('Felix Alba', 'Palmer_Lofton@gmail.com', '3813 Hope St', 'Hoopeston', '(765) 713-9006', 'F', 'Widow'),
    ('Eusebia Noland', 'Abernathy@gmail.com', '1168 Lake Circle', 'Concord', '(447) 838-0332', 'F', 'Single'),
    ('Denisha Mcginnis', 'Adaline_Abbott@gmail.com', '74 Burwood Way', 'Brookings', '(730) 273-6683', 'F', 'Single'),
    ('Stanford Sullivan', 'Shayne_Britton589@gmail.com', '3836 Hunting Hill Pkwy', 'Beavercreek', '(812) 252-0427', 'F', 'Married'),
    ('Nathan Salisbury', 'mxwygtmf_ahjpwboxdy@gmail.com', '3603 Stonewood Ct', 'Dublin', '(977) 813-8110', 'M', 'Married'),
    ('Burton Bunnell', 'Steve.A.Pape@outlook.com', '3490 Quailwood Street', 'Breese', '(826) 366-1014', 'M', 'Single'),
    ('Adah Jameson', 'Ivan.Southern98@gmail.com', 'NULL', 'Bedford Heights', '(914) 159-1651', 'M', 'Single'),
    ('Adam Geer', 'Darell_Centeno27@gmail.com', '402 Bayview Avenue', 'Aberdeen', '(961) 069-2786', 'M', 'Single'),
    ('Freeman Selby', 'Shanta.Beaver89@outlook.com', '647 Hidden Front Blvd', 'Pleasant Prairie', '(768) 048-0640', 'F', 'Divorced'),
    ('Laura Barger', 'GregoryMurrell@gmail.com', '3744 Woodhurst Pkwy', 'Chickasaw', '(790) 495-8216', 'F', 'Single'),
    ('Ariel Hermann', 'rfgxqoso9811@gmail.com', '683 SW Stonewood Way', 'Brigantine', '(552) 037-7186', 'M', 'Married'),
    ('Adam Maddox', 'Violette_Maxey368@gmail.com', '2254 W Riverview Lane', 'Merrill', '(247) 811-3933', 'F', 'Married'),
    ('Winnifred Brantley', 'Sanderson@gmail.com', '1314 New Glenwood Hwy', 'Lincoln Park', '(594) 490-9628', 'M', 'Divorced'),
    ('Gayle Baugh', 'Dennis@gmail.com', '781 North Hunting Hill Ln', 'Lompoc', '(438) 866-0472', 'M', 'Single'),
    ('Delcie Abney', 'Shifflett@gmail.com', '502 New Highland Highway', 'Madisonville', '(227) 049-9918', 'M', 'NULL'),
    ('Kasey Furr', 'Abbie.Watts@gmail.com', '2961 Deepwood Dr', 'Arlington', '(768) 693-9345', 'M', 'Divorced'),
    ('Gertie Abel', 'AlessandraNMckenzie72@gmail.com', '1156 Town Avenue', 'North Richland Hills', '(487) 479-9336', 'F', 'Widowed'),
    ('Myles Angel', 'mivxztrm_txjxxsw@gmail.com', '2008 Town Cir', 'Brenham', '(857) 863-6779', 'M', 'Single'),
    ('Jerome Gipson', 'Killian@outlook.com', 'NULL', 'Chehalis', 'NULL', 'F', 'Married'),
    ('Lilla Perez', 'Maness@outlook.com', 'NULL', 'Big Rapids', '(104) 855-4937', 'M', 'Married'),
    ('Josephine Norwood', 'KimberlieCrocker@outlook.com', '81 Beachwood Lane', 'Lindale', '(273) 600-9445', 'M', 'Married'),
    ('Elli Robertson', 'oxdngcmz8118@gmail.com', '51 Stonewood Pkwy', 'Sheridan', '(553) 638-6830', 'M', 'Divorced'),
    ('Curtis Hutson', 'Tiffanie.Romero27@outlook.com', '725 NW Waterview Way', 'Cathedral City', '(442) 344-5339', 'M', 'Married'),
    ('Melia Gates', 'Gable@gmail.com', '75 Beachwood Way', 'San Angelo', '(535) 013-0514', 'F', 'Married'),
    ('Marc Pickering', 'Myrtle_Bernard@gmail.com', '222 Burwood Pkwy', 'Fair Haven', '(875) 375-2382', 'F', 'Single'),
    ('Alida Jobe', 'Raynor8@gmail.com', '959 East Meadowview Drive', 'Snoqualmie', '(610) 362-5075', 'M', 'Married'),
    ('Cordelia Key', 'Sipes449@gmail.com', '2004 Mountain Dr', 'Philadelphia', '(243) 459-7372', 'M', 'Single'),
    ('Reba Gregg', 'Batson@gmail.com', '2008 3rd Ct', 'Valdosta', '(845) 678-6842', 'M', 'Married'),
    ('Jarod Bourgeois', 'ReaReyna391@outlook.com', '894 Old Rock Hill Way', 'Williams', '(384) 573-9515', 'F', 'Single'),
    ('Oliva Coble', 'SeeleyJ@gmail.com', '2274 E Lake Ct', 'Ringwood', '(135) 721-2385', 'M', 'Married'),
    ('Corey Musgrove', 'AbbieAbel@gmail.com', '1052 Deepwood Cir', 'Walnut Ridge', '(533) 039-4249', 'M', 'Divorced'),
    ('Bud Grubbs', 'Monty.Swan5@outlook.com', '138 1st Drive', 'Mahtomedi', '(649) 790-3129', 'M', 'Married'),
    ('Newton Graves', 'SteinerK@gmail.com', '2747 W Hope Hwy', 'Star', '(861) 866-2316', 'F', 'Married'),
    ('Tamica Goins', 'Daily37@gmail.com', '3082 West Quailwood Loop', 'Lewisville', '(403) 014-5022', 'F', 'Single'),
    ('Bertram Herzog', 'AddieTrice329@gmail.com', '609 Rose Hill Court', 'Winthrop Harbor', '(153) 734-4222', 'M', 'Single'),
    ('Malcolm Coward', 'Caballero313@gmail.com', '238 Pine Tree Dr', 'Park Ridge', 'NULL', 'M', 'Married'),
    ('Carley Valdez', 'uvrguf247@outlook.com', '17 Bayview Lane', 'Big Spring', '(821) 308-8608', 'F', 'Single'),
    ('Lizzie Krueger', 'Jewel.Albers24@outlook.com', '3747 Sharp Hill Dr', 'Champlin', '(864) 550-3567', 'F', 'NULL'),
    ('Celestine Hong', 'NULL', 'NULL', 'Beckley', '(360) 865-3659', 'F', 'Single'),
    ('Shonda Leake', 'Oliva_Caskey572@gmail.com', '327 New Church St', 'Albion', '(598) 443-5163', 'M', 'Single'),
    ('Hubert Waldrop', 'NULL', '2147 Riverview Dr', 'Aberdeen', '(995) 647-4714', 'F', 'Married'),
    ('Alphonso Meeks', 'Nannie_Farr@outlook.com', '2621 Mountain Circle', 'Cahokia', '(447) 684-3013', 'F', 'Single'),
    ('Aimee Stamm', 'mcvgy02@gmail.com', '806 Rose Hill Highway', 'Clarksville', 'NULL', 'M', 'NULL'),
    ('Sonia Ackerman', 'Mcnamara616@gmail.com', '3566 Old Hope Cir', 'Canal Fulton', '(866) 682-6586', 'M', 'Married'),
    ('Bertrada Zabel', 'AbrahamAcevedo@hotmail.com', 'Monett', 'Middlesbrough', '(564) 517-5025', 'M', 'Divorced'),
    ('Heiderose Blind', 'Jude_High169@hotmail.com', 'NULL', 'Stoke-on-Trent', '(684) 186-0087', 'F', 'Married'),
    ('Joko Adler', 'Bauer@hotmail.com', 'Hanover', 'Oxford', '(260) 313-6443', 'M', 'Single'),
    ('Hemma Küchenmeister', 'Alarcon@hotmail.com', 'West Bountiful', 'Liverpool', '(868) 864-8718', 'M', 'Married'),
    ('Helwig Hummel', 'gndd9978@hotmail.com', 'Kiryas Joel', 'Milton Keynes', '(451) 929-8321', 'M', 'Single'),
    ('Orthey Feuerbach', 'NULL', 'NULL', 'Gloucester', '(133) 683-0582', 'F', 'Single'),
    ('Hannfried Blume', 'Palmer_Lofton@hotmail.com', 'Hampton', 'West Bromwich', '(765) 713-9006', 'F', 'Widow'),
    ('Xenja Bohnke', 'Abernathy@hotmail.com', 'Watauga', 'Colchester', '(447) 838-0332', 'F', 'Single'),
    ('Selinda Reinrhard', 'Adaline_Abbott@hotmail.com', 'River Rouge', 'London', '(730) 273-6683', 'F', 'Single'),
    ('Pontianus Unger', 'Shayne_Britton589@hotmail.com', 'Cleburne', 'Huddersfield', '(812) 252-0427', 'F', 'Married'),
    ('Berengar Gering', 'mxwygtmf_ahjpwboxdy@hotmail.com', 'Valdosta', 'Walsall', '(977) 813-8110', 'M', 'Married'),
    ('Clemendina Singer', 'Steve.A.Pape@outlook.com', 'Centralia', 'Wolverhampton', '(826) 366-1014', 'M', 'Single'),
    ('Adine  Abicht', 'Ivan.Southern98@hotmail.com', 'NULL', 'Peterborough', '(914) 159-1651', 'M', 'Single'),
    ('Falina Fischer', 'Darell_Centeno27@hotmail.com', 'Aberdeen', 'Sheffield', '(961) 069-2786', 'M', 'Single'),
    ('Lovis Kloz', 'Shanta.Beaver89@outlook.com', 'Peekskill', 'Sunderland', '(768) 048-0640', 'F', 'Divorced'),
    ('Amrei Menger', 'GregoryMurrell@hotmail.com', 'Presque Isle', 'Newcastle upon Tyne', '(790) 495-8216', 'F', 'Single'),
    ('Catrin Niemann', 'rfgxqoso9811@hotmail.com', 'Madera', 'Bolton', '(552) 037-7186', 'M', 'Married'),
    ('Conny Dippel', 'Violette_Maxey368@hotmail.com', 'Burbank', 'Watford', '(247) 811-3933', 'F', 'Married'),
    ('Armgard Gerngross', 'Sanderson@hotmail.com', 'El Monte', 'Coventry', '(594) 490-9628', 'M', 'Divorced'),
    ('Korth Schiefer', 'Dennis@hotmail.com', 'Sherwood', 'Slough', '(438) 866-0472', 'M', 'Single'),
    ('Lenchen Zinger', 'Shifflett@hotmail.com', 'Poteau', 'Bournemouth', '(227) 049-9918', 'M', 'NULL'),
    ('Barthel  Zenner', 'Abbie.Watts@hotmail.com', 'Oxford', 'York', '(768) 693-9345', 'M', 'Divorced'),
    ('Krispin Zeiger', 'AlessandraNMckenzie72@hotmail.com', 'Troutdale', 'Luton', '(487) 479-9336', 'F', 'Widowed'),
    ('Wilbrecht Ebel', 'mivxztrm_txjxxsw@hotmail.com', 'Palm Bay', 'Sutton Coldfield', '(857) 863-6779', 'M', 'Single'),
    ('Dieter Gardenberg', 'Killian@outlook.com', 'NULL', 'Crawley', 'NULL', 'F', 'Married'),
    ('Rüder Geller', 'Maness@outlook.com', 'NULL', 'Ipswich', '(104) 855-4937', 'M', 'Married'),
    ('California Zeiger', 'KimberlieCrocker@outlook.com', 'Malone', 'Bradford', '(273) 600-9445', 'M', 'Married'),
    ('Fredegar Menzel', 'oxdngcmz8118@hotmail.com', 'Kaysville', 'Southampton', '(553) 638-6830', 'M', 'Divorced'),
    ('Lisa-Maria Geller', 'Tiffanie.Romero27@outlook.com', 'Coachella', 'Manchester', '(442) 344-5339', 'M', 'Married'),
    ('Aurion  Stumpf', 'Gable@hotmail.com', 'Aberdeen', 'Plymouth', '(535) 013-0514', 'F', 'Married'),
    ('Friedwart Möbius', 'Myrtle_Bernard@hotmail.com', 'Slatington', 'Kingston upon Hull', '(875) 375-2382', 'F', 'Single'),
    ('Cölestin Köstlin', 'Raynor8@hotmail.com', 'Satellite Beach', 'Dudley', '(610) 362-5075', 'M', 'Married'),
    ('Abeline  Gelen', 'Sipes449@hotmail.com', 'Amsterdam', 'Swindon', '(243) 459-7372', 'M', 'Single'),
    ('Balte  Feierbach', 'Batson@hotmail.com', 'Washington Court House', 'Northampton', '(845) 678-6842', 'M', 'Married'),
    ('Chlothar Bohrmann', 'ReaReyna391@outlook.com', 'Absecon', 'Derby', '(384) 573-9515', 'F', 'Single'),
    ('Dietlana Kronberg', 'SeeleyJ@hotmail.com', 'Melrose Park', 'Poole', '(135) 721-2385', 'M', 'Married'),
    ('Mirinda Schwarz', 'AbbieAbel@hotmail.com', 'Hazel Park', 'Leeds', '(533) 039-4249', 'M', 'Divorced'),
    ('Diepold Buchholz', 'Monty.Swan5@outlook.com', 'Lakeland', 'Southend-on-Sea', '(649) 790-3129', 'M', 'Married'),
    ('Janeric Pritzel', 'SteinerK@hotmail.com', 'Herndon', 'Brighton', '(861) 866-2316', 'F', 'Married'),
    ('Adriane  Finkelstein', 'Daily37@hotmail.com', 'Warwick', 'Norwich', '(403) 014-5022', 'F', 'Single'),
    ('Volbrecht Brandt', 'AddieTrice329@hotmail.com', 'Collinsville', 'Telford', '(153) 734-4222', 'M', 'Single'),
    ('Haiko Zenner', 'Caballero313@hotmail.com', 'Cheboygan', 'Birmingham', 'NULL', 'M', 'Married'),
    ('Avenell Rüdiger', 'uvrguf247@outlook.com', 'Olympia Fields', 'Eastbourne', '(821) 308-8608', 'F', 'Single'),
    ('Annalena Genkel', 'Jewel.Albers24@outlook.com', 'Lewisville', 'Portsmouth', '(864) 550-3567', 'F', 'NULL'),
    ('Haita Rosenblatt', 'NULL', 'NULL', 'Bristol', '(360) 865-3659', 'F', 'Single'),
    ('Yente Ulbricht', 'Oliva_Caskey572@hotmail.com', 'Watauga', 'St Helens', '(598) 443-5163', 'M', 'Single'),
    ('Justus Dannenberg', 'NULL', 'Picayune', 'Blackburn', '(995) 647-4714', 'F', 'Married'),
    ('Ottfried Schneidermann', 'Nannie_Farr@outlook.com', 'Allegan', 'Leicester', '(447) 684-3013', 'F', 'Single'),
    ('Almute Ebert', 'mcvgy02@hotmail.com', 'Katy', 'Reading', 'NULL', 'M', 'NULL'),
    ('Friederun Appel', 'Mcnamara616@hotmail.com', 'Ste. Genevieve', 'Exeter', '(866) 682-6586', 'M', 'Married')
]

Varias_Ciudades = [
    ('Aberdeen','United Kingdom'),
    ('Albion','United States'),
    ('Arlington','United States'),
    ('Beavercreek','United States'),
    ('Beckley','United States'),
    ('Bedford Heights','United States'),
    ('Big Rapids','United States'),
    ('Big Spring','United States'),
    ('Birmingham','United Kingdom'),
    ('Blackburn','United Kingdom'),
    ('Bolton','United Kingdom'),
    ('Bournemouth','United Kingdom'),
    ('Bradford','United States'),
    ('Breese','United States'),
    ('Brenham','United States'),
    ('Brigantine','United States'),
    ('Brighton','United Kingdom'),
    ('Bristol','United Kingdom'),
    ('Brookings','United States'),
    ('Cahokia','United States'),
    ('Canal Fulton','United States'),
    ('Cathedral City','United States'),
    ('Champlin','United States'),
    ('Chehalis','United States'),
    ('Chickasaw','United States'),
    ('Clarksville','United States'),
    ('Clayton','United States'),
    ('Colchester','United Kingdom'),
    ('Concord','United States'),
    ('Coventry','United Kingdom'),
    ('Crawley','United States'),
    ('Derby','United States'),
    ('Dublin','United States'),
    ('Dudley','United Kingdom'),
    ('Eastbourne','United States'),
    ('Exeter','United Kingdom'),
    ('Fair Haven','United States'),
    ('Gloucester','United Kingdom'),
    ('Hoopeston','United States'),
    ('Huddersfield','United Kingdom'),
    ('Ipswich','United States'),
    ('Kings Point','United Kingdom'),
    ('Kingston upon Hull','United Kingdom'),
    ('Leeds','United Kingdom'),
    ('Leicester','United States'),
    ('Lewisville','United States'),
    ('Lincoln Park','United States'),
    ('Lindale','United States'),
    ('Liverpool','United Kingdom'),
    ('Lompoc','United States'),
    ('London','United Kingdom'),
    ('Luton','United Kingdom'),
    ('Madisonville','United States'),
    ('Mahtomedi','United States'),
    ('Manchester','United States'),
    ('Merrill','United States'),
    ('Middlesbrough','United Kingdom'),
    ('Milton Keynes','United Kingdom'),
    ('Mount Horeb','United States'),
    ('Newcastle upon Tyne','United Kingdom'),
    ('North Richland Hills','United States'),
    ('Northampton','United Kingdom'),
    ('Norwich','United Kingdom'),
    ('Oxford','United Kingdom'),
    ('Park Ridge','United States'),
    ('Peterborough','United Kingdom'),
    ('Philadelphia','United States'),
    ('Pleasant Prairie','United States'),
    ('Plymouth','United Kingdom'),
    ('Poole','United Kingdom'),
    ('Portsmouth','United States'),
    ('Reading','United Kingdom'),
    ('Ringwood','United States'),
    ('San Angelo','United States'),
    ('Scottdale','United States'),
    ('Sheffield','United Kingdom'),
    ('Sheridan','United States'),
    ('Slough','United Kingdom'),
    ('Snoqualmie','United States'),
    ('Southampton','United Kingdom'),
    ('Southend-on-Sea','United States'),
    ('St Helens','United Kingdom'),
    ('Star','United States'),
    ('Stoke-on-Trent','United Kingdom'),
    ('Sunderland','United States'),
    ('Sutton Coldfield','United Kingdom'),
    ('Swindon','United Kingdom'),
    ('Telford','United Kingdom'),
    ('Valdosta','United States'),
    ('Wabash','United States'),
    ('Walnut Ridge','United States'),
    ('Walsall','United Kingdom'),
    ('Watford','United Kingdom'),
    ('West Bromwich','United Kingdom'),
    ('Williams','United States'),
    ('Winthrop Harbor','United States'),
    ('Wolverhampton','United States'),
    ('York','United Kingdom')
]

Regiones = [
    ('United States','America'),
    ('United Kingdom','Europe')
]